/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revendedora;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Windows 7
 */
public class listarv extends javax.swing.JFrame {

    /**
     * Creates new form listarv
     */
    public listarv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTListagem = new javax.swing.JTable();
        jBatualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jTListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Modelo", "Marca", "Placa", "Cor", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTListagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTListagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 40, 580, 170);

        jBatualizar.setText("Atualizar");
        jBatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBatualizar);
        jBatualizar.setBounds(440, 220, 130, 23);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 220, 130, 23);

        jLabel1.setText("LISTAGEM DA ENTRADA E SAÍDA DE VEICULOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 230, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizarActionPerformed
     listar();
    }//GEN-LAST:event_jBatualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Menu x = new Menu();
    x.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTListagemMouseClicked
     alteracao();
    }//GEN-LAST:event_jTListagemMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    listar();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBatualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTListagem;
    // End of variables declaration//GEN-END:variables
private void listar(){
    String Comando = "select * from veiculo;";
    
         ResultSet rs;
         
         int l = 0;
         try{
             Conexao x = new Conexao();
             rs = x.consultar(Comando);
             
             while(rs.next()){
                 jTListagem.setValueAt(rs.getString("codv"), l, 0);
                  jTListagem.setValueAt(rs.getString("modelo"), l, 1);
                   jTListagem.setValueAt(rs.getString("marca"), l, 2);
                    jTListagem.setValueAt(rs.getString("placa"), l, 3);                        
                     jTListagem.setValueAt(rs.getString("cor"), l, 4);
                      jTListagem.setValueAt(rs.getString("status"), l, 5);
                        
                      l++;
             }
             
         }catch(SQLException ex){
             Logger.getLogger(listarv.class.getName()).log(Level.SEVERE,null,ex);
         }
    
}
private void alteracao(){
        int l = jTListagem.getSelectedRow();
        int cod = Integer.parseInt((String) jTListagem.getValueAt(l, 0));
        AlterarV x = new AlterarV(cod);
        x.setVisible(true);
}
}
