/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revendedora;

/**
 *
 * @author Windows 7
 */
public class Menu extends javax.swing.JFrame {
    
    
    
    
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMalterarF = new javax.swing.JMenuItem();
        jMlistarF = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMcadastroV = new javax.swing.JMenuItem();
        jMalterarV = new javax.swing.JMenuItem();
        jMlistarV = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(562, 0, 0, 224);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("SOFTWARE DE ENTRADA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 293, 29);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("E SAÍDA DE VEÍCULOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 100, 258, 29);

        jMenu3.setText("Funcionário");

        jMalterarF.setText("Alterar Perfil");
        jMalterarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterarFActionPerformed(evt);
            }
        });
        jMenu3.add(jMalterarF);

        jMlistarF.setText("Listar Funcionários");
        jMlistarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistarFActionPerformed(evt);
            }
        });
        jMenu3.add(jMlistarF);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Entrada e Saída  de Veículos ");

        jMcadastroV.setText("Cadastrar Veículo");
        jMcadastroV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcadastroVActionPerformed(evt);
            }
        });
        jMenu2.add(jMcadastroV);

        jMalterarV.setText("Alterar dados Veículos");
        jMalterarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterarVActionPerformed(evt);
            }
        });
        jMenu2.add(jMalterarV);

        jMlistarV.setText("Listar Veículos");
        jMlistarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistarVActionPerformed(evt);
            }
        });
        jMenu2.add(jMlistarV);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Deslogar");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMalterarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterarVActionPerformed
        AlterarV x = new AlterarV();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMalterarVActionPerformed

    private void jMalterarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterarFActionPerformed
       AlterarF x = new AlterarF();
       x.setVisible(true);
       dispose();
    }//GEN-LAST:event_jMalterarFActionPerformed

    private void jMlistarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistarFActionPerformed
        listarF x = new listarF();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMlistarFActionPerformed

    private void jMcadastroVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcadastroVActionPerformed
        CadastroV x = new CadastroV();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMcadastroVActionPerformed

    private void jMlistarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistarVActionPerformed
        listarv x = new listarv();
        x.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMlistarVActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TdL x = new TdL();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMalterarF;
    private javax.swing.JMenuItem jMalterarV;
    private javax.swing.JMenuItem jMcadastroV;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMlistarF;
    private javax.swing.JMenuItem jMlistarV;
    // End of variables declaration//GEN-END:variables
}
